ESSE ARQUIVO VAI TE DAR A PERMISSÃO DE PARTICIPAR DO PROJETO

BASTA MANDAR UM EMAIL PARA ESSE AQUI: cesinhadiscord@gmail.com 
COM AS SEGUINTES INFORMAÇÕES:

NOME:
IDADE(OPCIONAL):
PRINT DA PÁGINA INCIAL DO REPOSITÓRIO:

VAMOS RESPONDER COM UM: "VERIFICADO"
